---
title: "PCA and Manhattan plot"
author: "xyz"
date: "2021/11/4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(dplyr)
library(vegan)
library(ggrepel)
library(ggplot2)
library(phyloseq)
library(DESeq2)
```

```{r}
df <- readxl::read_xlsx("../data/mappingNew.xlsx")
df <- df[df$`#SampleID` %in% paste0("S", 22:30), ]
df2 <- data.frame(
  ID = df$`#SampleID`,
  Time = str_extract(df$Description, "Day[0-9]*"),
  Treatment = str_sub(str_split(df$Description, "_", simplify = T)[, 3], end =
                        -2)
)
# df2$Treatment[1:3]<-"Day0"
write.csv(df2,
          "../table/metaNew.csv",
          row.names = F)
```

# PCA

```{r}
otu <-
  read.csv("../table/OTU16S.csv")
otu <- otu[, 11:19]
otu <- prop.table(as.matrix(otu), 2)
meta <- read.csv("../table/metaNew.csv")
rownames(meta)<-meta$ID
meta<-meta[colnames(otu),]

pca <- rda(t(otu), scale = T)
importance <- summary(pca)[["cont"]][["importance"]]
siteScore <- summary(pca)[["sites"]]
tempDf <- cbind(x = siteScore[, 1],
                y = siteScore[, 2],
                meta)

PCAplot <- function(attri, labeled = F, fileName=" PCA.pdf")
{
  p <- ggplot(tempDf,
              aes(
                x = x,
                y = y,
                color = get(attri),
              )) +
    geom_point(size = 3) +
    xlab(paste0("PC1(", round(importance[2, 1] * 100, 2), "%)")) +
    ylab(paste0("PC2(", round(importance[2, 2] * 100, 2), "%)")) +
    theme(text = element_text(size = 20))
  p <- p + labs(color = attri)
  if (labeled == T)
    p <- p + geom_text_repel(aes(label = ID), max.overlaps = Inf)
  p + ggsave(paste0("../figure/newMeta/", attri, fileName),
             width = 8,
             height = 6)
}
PCAplot("Treatment")
PCAplot("Treatment",T," with ID PCA.pdf")
PCAplot("Time")
PCAplot("Time",T," with ID PCA.pdf")
```

# NMDS

```{r}
nmds <- metaMDS(t(otu), distance = 'bray', k = 2,try = 200)
tempDf <- cbind(
  x = nmds$points[, 1],
  y = nmds$points[, 2],
  meta
)
stress <- nmds$stress
NMDSplot <- function(attri, labeled = F, fileName=" NMDS.pdf")
{
  p <- ggplot(tempDf,
              aes(
                x = x,
                y = y,
                color = get(attri),
              )) +
    geom_point(size = 3) +
    xlab("MDS1") +
    ylab("MDS2") +
    labs(title = paste0("Stress=", round(stress, 3))) +
    theme(text = element_text(size = 20))
  p <- p + labs(color = attri)
  if (labeled == T)
    p <- p + geom_text_repel(aes(label = ID), max.overlaps = Inf)
  p + ggsave(paste0("../figure/newMeta/", attri, fileName),
             width = 8,
             height = 6)
}
NMDSplot("Treatment")
NMDSplot("Treatment",T," with ID NMDS.pdf")
NMDSplot("Time")
NMDSplot("Time",T," with ID NMDS.pdf")
```

# package phylo object

```{r}
otu <- read.csv("../table/OTU16S.csv")

otu_dna <- otu[, 11:19]
rownames(otu_dna) <- otu$OTU.ID
tax_dna <- otu[, c(20:26)]
rownames(tax_dna) <- otu$OTU.ID
treat_dna <- meta
rownames(treat_dna) <- meta$ID

otus = as.matrix(otu_dna)
taxa = as.matrix(tax_dna)
sampledata = treat_dna

OTU = otu_table(otus, taxa_are_rows = TRUE)
# Filter the number of OTU occurrences in the sample
OTU1 <- filter_taxa(OTU, function(x)
  sum(x > 0) > 1, TRUE)
# Filter the total OTU is less than 10
OTU2 <- prune_taxa(taxa_sums(OTU1) > 9, OTU1)
# rarefy
OTU <- rarefy_even_depth(
  OTU2,
  sample.size = min(sample_sums(OTU2)),
  rngseed = 9527,
  replace = TRUE,
  trimOTUs = TRUE,
  verbose = TRUE
)

TAX = tax_table(taxa)
sampledata = sample_data(sampledata)
phyloseqobj = phyloseq(OTU, TAX)
physeq1 = merge_phyloseq(phyloseqobj, sampledata)
physeq1
```

# Manhattan plot

```{r}
diagdds = phyloseq_to_deseq2(physeq1, ~ Treatment)
diagdds = DESeq(diagdds, test = "Wald", fitType = "parametric")

ManhattanPlot <- function(contrast1, contrast2, p) {
  res = results(diagdds, contrast = c("Treatment", contrast1, contrast2))
  alpha = p # Also available 0.05
  sigtab = res[which(res$padj <= alpha),]
  sigtab <- as(sigtab, "data.frame")
  sigtab <- na.omit(sigtab)
  sigtab = cbind(as(sigtab, "data.frame"),
                 as(tax_table(physeq1)[rownames(sigtab),], "matrix"))
  write.csv(
    sigtab,
    paste0(
      "../table/newMeta/",
      contrast1,
      " VS ",
      contrast2,
      " significant different abundance.csv"
    )
  )
  sigtab$neglog10p = -log10(sigtab$padj)
  sigtab$otu = rownames(sigtab)
  sigtab = arrange(sigtab, Phylum, Class, Order, Family, Genus)
  sigtab$otu = factor(sigtab$otu, levels = sigtab$otu)
  sigtab$num = 1:dim(sigtab)[1]
  sigtab[which(sigtab$log2FoldChange < -1), 'level'] <- 'Depleted'
  sigtab[which(sigtab$log2FoldChange > 1), 'level'] <- 'Enriched'
  sigtab <- sigtab[!is.na(sigtab$level),]
  topPhylum <- sort(table(sigtab$Phylum), decreasing = T)
  topPhylum <- topPhylum[topPhylum >= 2]
  topGenus <- sort(table(sigtab$Genus), decreasing = T)
  drawDf <- sigtab
  drawDf$Phylum[!(drawDf$Phylum %in% names(topPhylum))] <- "Others"
  drawDf$Phylum <- str_remove(drawDf$Phylum, "p__")
  drawDf$Genus[!(drawDf$Genus %in% names(topGenus))] <- "Others"
  drawDf$Genus <- str_remove(drawDf$Genus, "g__")
  drawDf <- arrange(drawDf, Phylum, Class, Order, Family, Genus)
  drawDf$num <- 1:nrow(drawDf)
  write.csv(
    drawDf,
    paste0(
      "../table/newMeta/",
      contrast1,
      " VS ",
      contrast2,
      " significant different abundance Top.csv"
    )
  )
  p <- ggplot(drawDf,
              aes(
                x = num,
                y = neglog10p,
                fill = Phylum,
                color = Phylum,
                size = abs(log2FoldChange),
                shape = level
              )) +
    geom_point(alpha = .7) +
    scale_x_continuous(
      breaks = 1:nrow(drawDf),
      labels = drawDf$Genus,
      name = "Genus"
    ) +
    ylab(expression(-log[10](FDR))) +
    # change legend size
    guides(fill = guide_legend(override.aes = list(size = 5)),
           shape = guide_legend(override.aes = list(size = 4))) +
    # change legend tittle
    scale_size_continuous(name = expression(log[2](FC)), breaks = c(2, 4, 6)) +
    scale_shape_manual(name = "Level", values = c(25, 24)) +
    # remove background
    theme(
      text = element_text(size = 15),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(
        fill = NA,
        color = "grey10",
        linetype = 1,
        size = 1.
      ),
      axis.text.x = element_text(
        angle = -90,
        vjust = 0.5,
        hjust = 0.01
      ),
      legend.key = element_blank(),
    )
  p + ggsave(
    paste0("../figure/newMeta/",
           contrast1,
           " VS ",
           contrast2, " Manhattan plot.pdf"),
    width = 18,
    height = 8
  )
  return(p)
}
StrawVsCK <- ManhattanPlot("Straw","CK",0.01)
StrawNVsCK <- ManhattanPlot("StrawN","CK",0.01)
StrawVsStrawN <- ManhattanPlot("Straw","StrawN",0.01)
```

# volcano plot

```{r}
judgeSignificance <- function(x, y) {
  if (x <= 0.05) {
    if (y <= -1)
      return ("down")
    else if (y >= 1)
      return ("up")
    else
      return ("no")
  }
  else
    return("no")
}

VolcanoPlot <- function(df) {
  colnames(df) <- c("FDR", "FC")
  df$size <- -log10(df$FDR)
  df <-
    cbind(df, significance = factor(mapply(judgeSignificance, df$FDR, df$FC)))
  ggplot(df, aes(FC, -1 * log10(FDR))) +
    geom_point(
      aes(
        fill = significance,
        colour = significance,
        size = size
      ),
      shape = 21,
      alpha = 0.6
    ) +
    # Resize the point from 0.1 to 10
    scale_size(range = c(.1, 10)) +
    theme(text = element_text(size = 20)) +
    guides(
      fill = guide_legend(override.aes = list(size = 10)),
      size = FALSE,
      colour = FALSE
    ) +
    scale_fill_discrete(labels = paste(levels(df$significance), table(df$significance))) +
    labs(x = expression(log[2](FC)), y = expression(-log[10](FDR))) +
    geom_hline(yintercept = -log10(0.05), linetype = 4) +
    geom_vline(xintercept = c(-log2(2), log2(2)), linetype = 4) +
    # Limit the scope of the drawing, make it left-right symmetric, and add linear coordinates
    scale_x_continuous(limits = c(-15, 15), breaks = sort(c(seq(
      -15,
      15, length.out = 7
    ),-1, 1))) +
    scale_y_continuous(breaks = sort(c(seq(
      0,
      8, length.out = 5
    ),1.30)))
}

drawVolcanoPlot <- function(contrast1, contrast2) {
  res = results(diagdds, contrast = c("Treatment", contrast1, contrast2))
  sigtab <- as(res, "data.frame")
  sigtab <- na.omit(sigtab)
  sigtab = sigtab[, c("padj", "log2FoldChange")]
  p <- VolcanoPlot(sigtab)
  p + ggsave(
    paste0(
      "../figure/newMeta/",
      contrast1,
      " VS ",
      contrast2,
      " Volcano plot.pdf"
    ),
    width = 8,
    height = 6
  )
  return(p)
}
StrawVsCK <- drawVolcanoPlot("Straw", "CK")
StrawNVsCK <- drawVolcanoPlot("StrawN", "CK")
StrawVsStrawN <- drawVolcanoPlot("Straw", "StrawN")
```

